### ISSUE TITLE
Exception on 1 2 1 1   3 4 5 6 7 8

### ISSUE THREAD

**Issue by bunea** [adrobotics/BlackBoxGaming-Engine#1]
Exception in thread "LWJGL Application" java.lang.NullPointerException
    at com.blackboxgaming.engine.collision.contactlistener.ContactListener2D.changeToRandomDirection(ContactListener2D.java:46)
    at com.blackboxgaming.engine.collision.contactlistener.ContactListener2D.beginContact(ContactListener2D.java:26)
    at com.badlogic.gdx.physics.box2d.World.beginContact(World.java:985)
    at com.badlogic.gdx.physics.box2d.World.jniStep(Native Method)
    at com.badlogic.gdx.physics.box2d.World.step(World.java:689)
    at com.blackboxgaming.engine.systems.PhysicsSystem2D.update(PhysicsSystem2D.java:71)
    at com.blackboxgaming.engine.managers.SystemManager.update(SystemManager.java:115)
    at com.blackboxgaming.engine.Engine.update(Engine.java:39)
    at com.blackboxgaming.engine.BlackBoxGame.render(BlackBoxGame.java:58)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:223)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

**Comment by adrobotics** [comment]
Working on it

**Comment by adrobotics** [comment]
The project was in "feature development" mode, not in demo mode t the time this happened. Fixed in commit 5fc337763a39e6f646360e9ec3a4ac812ef7cb36
